### ISSUE TITLE
Design/implement class to record performance measurements

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/CSCN73060-Group6#14]
Basically what we want is a class that exists during the running of the program (so it gets initialized in the beginning of the program). The class itself will act as a timer and can measure the latency of workloads. I feel like we would want a helper class here (1 class that collects latency results and 1 class that represents a single latency result)

So in our program, we might have something like this:
```
int main(void) {
   LatencyTimer timer();
   ...

   LatencyMeasurement measurement(workload_id); // Starts timer as soon as objected is instantiated
   ... // Workload starts and completes here
   measurement.stop();
   timer.add(measurement);
   
   ...
   timer.save_result("performance_data"); // will save with subdirectories inside performance_data/

   return 0;
}
```

Things to do:
- [x] Data to ~~receive~~ construct: latencies 
- [x] File format: JSNO
- [x] Design constructor, methods
- [x] Serialization/deserialization (to/from JSON, for example)

**Comment by ehharvey** [comment]
How to store the data:

We have a folder called performance_data (or something).

performance_data/[profiler]/[date + time]/[workload]/*.json

Each json (or whatever format) would contain measurement (latency or throughput, etc.)
```
{
    "latency": "3ms"
}
```

**Comment by Amanuel-Negussie** [comment]
![image](https://user-images.githubusercontent.com/74369791/215291413-c70cea6b-d399-4ca7-b1fe-639b22f2e025.png)
I like this precise time measurement option for precisely measuring the latency.

https://stackoverflow.com/questions/14337278/precise-time-measurement
