### ISSUE TITLE
Client implementation (File IO)

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/CSCN73060-Group6#56]
- [ ] Know that the CSV file has the column names AND first row in the first line of the file :exploding_head: 
- [x] Read a `time`/`fuel` pair as a string
- [ ] Add a null terminator at the comma between `time` and `fuel`
- [x] Parse the time part using `strptime` using `format` string `%d_%m_%Y %H:%M:%S`
- [ ] Ensure that ^^ works (unit tests??)
- [x] Calculate `secondDelta`
- [x] Calculate `fuelLevel`
- [ ] (Bonus: Make file IO occur on its own thread. io_service could be a way to do this)

**Comment by Jacky-Lam-CY** [comment]
The CsvReader doesn't read the column name, if we need the column name, we can implement it later.
To get the fuel level, first remove the dot, then convert the string to integer.
